"""add clause review/correction tracking columns

Revision ID: 190a827ae2ac
Revises: 5a81feead0dd
Create Date: 2026-08-18 11:21:15.725972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190a827ae2ac'
down_revision = '5a81feead0dd'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-scoped: the autogenerated version bundled in a large amount of unrelated
    # pre-existing schema drift (index drops, column type changes on unrelated tables,
    # and a column drop on project_evidence_artifacts) -- none of that was reviewed or
    # intended, so it's deliberately excluded. This migration does ONLY the clause
    # review/correction tracking columns.
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_assigned_clause_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clause_type_reviewed_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('clause_type_reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clause_type_review_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_clauses_clause_type_reviewed_by', 'Users', ['clause_type_reviewed_by'], ['id'])

    # One-time backfill: for every existing clause, the current clause_type IS what the
    # AI originally assigned (no human-review mechanism existed until now) -- preserve it
    # so historical data isn't left with an empty ai_assigned_clause_type.
    op.execute('''UPDATE clauses SET ai_assigned_clause_type = clause_type WHERE ai_assigned_clause_type IS NULL''')


def downgrade():
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clauses_clause_type_reviewed_by', type_='foreignkey')
        batch_op.drop_column('clause_type_review_notes')
        batch_op.drop_column('clause_type_reviewed_by')
        batch_op.drop_column('clause_type_reviewed_at')
        batch_op.drop_column('ai_assigned_clause_type')
        batch_op.drop_column('intent_summary')
